export const users = [
  {
    _id: "1",
    name: "Alice Johnson",
    email: "alice@example.com",
    contactNumber: "+1-555-1234",
    address: "123 Main St, Springfield",
    profile: "https://i.pravatar.cc/100?img=1",
    role: "admin",
    isBlock: false,
  },
  {
    _id: "2",
    name: "Bob Smith",
    email: "bob@example.com",
    contactNumber: "+1-555-5678",
    address: "456 Elm St, Shelbyville",
    profile: "https://i.pravatar.cc/100?img=2",
    role: "user",
    isBlock: true,
  },
  {
    _id: "3",
    name: "Charlie Lee",
    email: "charlie@example.com",
    contactNumber: "+1-555-8765",
    address: "789 Oak St, Ogdenville",
    profile: "https://i.pravatar.cc/100?img=3",
    role: "moderator",
    isBlock: false,
  },
  {
    _id: "4",
    name: "Diana Prince",
    email: "diana@example.com",
    contactNumber: "+1-555-4321",
    address: "101 Pine St, North Haverbrook",
    profile: "https://i.pravatar.cc/100?img=4",
    role: "user",
    isBlock: false,
  },
  {
    _id: "5",
    name: "Ethan Wright",
    email: "ethan@example.com",
    contactNumber: "+1-555-2468",
    address: "202 Maple St, Capital City",
    profile: "https://i.pravatar.cc/100?img=5",
    role: "admin",
    isBlock: true,
  },
];
